### PR TITLE
Jv disable tests for failing vms

### PR DESCRIPTION
**Pull request by JoukoVirtanen**
## Description

Disabling ConnScraper tests for sles-12 and ubuntu-2204-lts

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

CI is sufficient

### CODE REVIEW

**Comment by JoukoVirtanen** [comment]
First time the following tests failed. Seem to be infrastructure related failures.

rhel-7-ebpf-integration-tests
rhel-86-sap-ebpf-integration-tests
ubuntu-2004-lts-kernel-module-integration-tests

**Comment by JoukoVirtanen** [comment]
> First time the following tests failed. Seem to be infrastructure related failures.
> 
> rhel-7-ebpf-integration-tests rhel-86-sap-ebpf-integration-tests ubuntu-2004-lts-kernel-module-integration-tests

All tests passed on the second run

**Comment by JoukoVirtanen** [comment]
Accidentally closed PR after all tests passed :(

rhel-7-ebpf-integration-tests failed due to ssh issue

/test rhel-7-ebpf-integration-tests

**Review by ovalenti — APPROVED** [review]
Thanks for the fix :+1:

**Pull request merged**
