### PR TITLE
ROX-12735: add automation to enter new community PRs to OSS Triage board automatically

### PR DESCRIPTION
**Pull request by tommartensen**
## Description

New external PRs are labeled with `external-contributor` and added to the OSS Triage board.
Tested in https://github.com/stackrox/dev-docs/pull/17. 

## Checklist
- ~[ ] Investigated and inspected CI test results~
- ~[ ] Updated documentation accordingly~

**Automated testing**
  - ~[ ] Added unit tests~
  - ~[ ] Added integration tests~
  - ~[ ] Added regression tests~

If any of these don't apply, please comment below.

### CODE REVIEW

**Review by Maddosaurus — APPROVED** [review]
LGTM! 🚀

**Comment by Molter73** [comment]
@Maddosaurus, we kinda broke OSCI yesterday, sorry about that. We are working to get it back up and running and it is unrelated to this changes.

**Review by Molter73 — COMMENTED** [review]
Could we unify this workflow with https://github.com/stackrox/collector/blob/master/.github/workflows/add-issue-to-triage.yml? Their goal seems to be pretty much the same, add issues/prs onto the OSS board.

**Comment by tommartensen** [comment]
@Molter73 - good idea, but while the goal is the same, we only want to add only _external_ Pull Requests. The first job of this new workflow is the filter for that. We would need to implement another condition into that to distinguish between issues and PRs. I think it's cleaner to have separate actions for each type of input.

**Comment by tommartensen** [comment]
> We are working to get it back up and running and it is unrelated to these changes.

You can ping me in the PR when I can rebase or re-run tests. Right now `Merging is blocked`.

**Review by Molter73 — APPROVED** [review]
/lgtm

**Pull request merged**
