### PR TITLE
Update submodules, migrate to luajit2

### PR DESCRIPTION
**Pull request by yselkowitz**
## Description

- Update stackrox submodule
- Switch from luajit to luajit2
- Add jsoncpp submodule

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Updated documentation accordingly

**Automated testing**
  - [ ] Added unit tests
  - [ ] Added integration tests
  - [ ] Added regression tests

If any of these don't apply, please comment below.

## Testing Performed

Relying on CI

### CODE REVIEW

**Comment by yselkowitz** [comment]
all tests have passed
/assign @robbycochran

**Review by robbycochran — APPROVED** [review]
LGTM -- Thanks @yselkowitz

**Comment by yselkowitz** [comment]
@robbycochran I have no permissions in this org or this repo, so I'll need you to merge.

**Pull request merged**
