### PR TITLE
Add slack notifications

### PR DESCRIPTION
**Pull request by erthalion**
## Description

Notify on failed integration tests & unit tests on the main branch.

## Checklist
- [ ] Investigated and inspected CI test results
~- [ ] Updated documentation accordingly~

## Testing Performed

Local testing of the script.

### CODE REVIEW

**Review by ovalenti — COMMENTED** [review]
I wonder if the ` || (notify)` construct will mask the failed test. Indeed, this clause will likely return 0.
When a test failes, is Make still marking the job as failed with this modification ?

**Comment by erthalion** [comment]
> I wonder if the ` || (notify)` construct will mask the failed test. Indeed, this clause will likely return 0. When a test failes, is Make still marking the job as failed with this modification ?

Right, it will be awkward. I've made the notification wrapper to keep the exit code.

**Review by ovalenti — APPROVED** [review]
It is difficult to test this is a realistic environment until it gets actually merged...

The code looks good to me !

**Comment by erthalion** [comment]
> It is difficult to test this is a realistic environment until it gets actually merged...

The testing is indirectly happening here https://github.com/openshift/release/pull/31547

**Pull request merged**
